//done
package Frames;

import Frames.ProgramError.ErrorDisplay;
import Frames.ProgramError.Instruction;
import Frames.ProgramError.Report;
import Frames.ProgramError.Troubleshoot;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

public class askforupdate extends javax.swing.JFrame {

    String fromyear,name,lastyear;
    private final Dimension SCREEN_SIZE=Toolkit.getDefaultToolkit().getScreenSize();

    public askforupdate(String year,String last,String name1) {
        initComponents();
        name=name1;
        fromyear=year;
        lastyear=last;
        String s="                   Update Bill for "+name+" to next year "+next(year)+"              ";
        jLabel1.setText(s);
        int w1=jLabel1.getFontMetrics(jLabel1.getFont()).stringWidth(s);
        this.setSize(w1+40,120);
        this.setLocation((SCREEN_SIZE.width-this.getWidth())/2,(SCREEN_SIZE.height-this.getHeight())/2);
        jButton1.addKeyListener(listen_to_key);
        jButton2.addKeyListener(listen_to_key);
    }
        KeyListener listen_to_key = new KeyListener() {

            public void keyTyped(KeyEvent e) {
            }

            public void keyPressed(KeyEvent evt) {
                if(evt.getKeyCode()==KeyEvent.VK_Y)
                    jButton1ActionPerformed(null);

                else if (evt.getKeyCode()==KeyEvent.VK_N)
                    jButton2ActionPerformed(null);

            }

            public void keyReleased(KeyEvent e) {
            }
        };

    private askforupdate() {
        initComponents();
    }

    public final String next(String year1){
            if(year1.equals("")||year1.equals("Year out of range"))
            return year1;
                String y0 = "";
                try{
                    int left=Integer.parseInt(year1.substring(0, year1.indexOf("-")))+1;
                int right=Integer.parseInt(year1.substring(year1.indexOf("-")+1, year1.length()))+1;
                if(year1.equals(lastyear)){
                    return "Year out of range";
                }
                if(left<10)
                    y0="0";
                y0=y0+String.valueOf(left)+"-";
                if(right<10)
                    y0+="0";
                y0+=String.valueOf(right);
        }catch(final Exception e){
            //bugno sem121Wia\\ehentx
            final ErrorDisplay err=new ErrorDisplay("sem121Wia\\ehentx");
            err.setVisible(true);
            err.addTroubleshootAction(new Troubleshoot() {

                public void doAction() {
                    new Instruction("Ensure that there in no other folder than year's folders (e.g. 12-13 is OK but anything else like app-78 is not) in bills folder and restart.").setVisible(true);
                }
            });
            err.addReportAction(new Report() {

                public void reportAction() {
                    err.setStackTraceElement(e.getStackTrace());
                    err.addAdditionalReporting("Illegal folder is present in bills folder.");
                }
            });
            Thread.currentThread().stop();
        }
                return y0;
                }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Update the Bill");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setOpaque(true);

        jButton1.setText("Yes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("No");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(602, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-796)/2, (screenSize.height-116)/2, 796, 116);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                    decision=true;
                    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                    decision=false;
                    dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new askforupdate("00-01","fdsffffffffffffffffffffffsfsdfs","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
boolean decision;

}
