/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * billhead1.java
 *
 * Created on Jun 4, 2011, 3:47:37 AM
 */

package Frames;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ci
 */
public class billhead1 extends javax.swing.JFrame {

    /** Creates new form billhead1 */
    public billhead1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l1cb = new javax.swing.JCheckBox();
        l2cb = new javax.swing.JCheckBox();
        l3cb = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        line1 = new javax.swing.JTextField();
        line2 = new javax.swing.JTextField();
        line3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Regisration Step-3");

        l1cb.setText("Line 1 : ");
        l1cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1cbActionPerformed(evt);
            }
        });

        l2cb.setText("Line 2 : ");
        l2cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2cbActionPerformed(evt);
            }
        });

        l3cb.setText("Line 3 : ");
        l3cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3cbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Title for the Index Sheet of Bills");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        line1.setEnabled(false);

        line2.setEnabled(false);

        line3.setEnabled(false);

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Note : Use ## for Current Year");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l1cb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(line1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l2cb)
                                .addGap(6, 6, 6)
                                .addComponent(line2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l3cb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(line3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1cb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l2cb)
                    .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l3cb)
                    .addComponent(line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-420)/2, (screenSize.height-224)/2, 420, 224);
    }// </editor-fold>//GEN-END:initComponents

    private void l1cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1cbActionPerformed
        // TODO add your handling code here:
        if(l1cb.isSelected())
            line1.setEnabled(true);
        else
            line1.setEnabled(false);
    }//GEN-LAST:event_l1cbActionPerformed

    private void l2cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2cbActionPerformed
        // TODO add your handling code here:
        if(l2cb.isSelected())
            line2.setEnabled(true);
        else
            line2.setEnabled(false);
    }//GEN-LAST:event_l2cbActionPerformed

    private void l3cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3cbActionPerformed
        // TODO add your handling code here:
        if(l3cb.isSelected())
            line3.setEnabled(true);
        else
            line3.setEnabled(false);
    }//GEN-LAST:event_l3cbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            File f1 = new File(System.getProperty("user.dir") + "/impinfo.txt");
            scanner read = null;
            read = new scanner(new InputStreamReader(new FileInputStream(f1), "UTF-8"));
            File f = File.createTempFile("temp", ".txt");
            writer o = new writer();
            o.init(new FileWriter(f));
            o.write(read.nextLine()+"\r\n");
            o.write(read.nextLine()+"\r\n");
            o.write(read.nextLine()+"\r\n");
            o.write("%$"+line1.getText()+"%$"+line2.getText()+"%$"+line3.getText()+"%$\r\n");
            while(read.hasNextLine()){
                o.write(read.nextLine()+"\r\n");
            }
            o.close();
            read.close();
            read = new scanner(new InputStreamReader(new FileInputStream(f), "UTF-8"));
            o.init(new FileWriter(f1));
            while(read.hasNextLine())
                o.write(read.nextLine()+"\r\n");
            o.close();
            read.close();
        } catch (Exception ex) {
        }
        dispose();
        new billing().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            writer o = new writer();
            o.init(new FileWriter(new File(System.getProperty("user.dir") + "/impinfo.txt")));
            o.write("\r\n");
            o.close();
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(billhead1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            writer o = new writer();
            o.init(new FileWriter(new File(System.getProperty("user.dir") + "/impinfo.txt")));
            o.write("\r\n");
            o.close();
            dispose();
            new billhead().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(billhead1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public String[] getIndexSheetHead(){
        scanner read=null;
              try {
                    read = new scanner(new InputStreamReader(new FileInputStream(new File(System.getProperty("user.dir")+"/impinfo.txt")), "UTF-8"));
                } catch (Exception ex) {
                    Logger.getLogger(bills.class.getName()).log(Level.SEVERE, null, ex);
                }
        read.nextLine();
        read.nextLine();
        read.nextLine();
        StringBuffer g=new StringBuffer(read.nextLine());
        String[] arr=new String[3];
        int i=0,c=0,remi;
        while((remi=g.indexOf("%$", i+2))!=-1){
            arr[c++]=g.substring(i+2, i=remi);
        }
        return arr;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billhead1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox l1cb;
    private javax.swing.JCheckBox l2cb;
    private javax.swing.JCheckBox l3cb;
    private javax.swing.JTextField line1;
    private javax.swing.JTextField line2;
    private javax.swing.JTextField line3;
    // End of variables declaration//GEN-END:variables

}
