//done
package Frames;

import Frames.ProgramError.ErrorDisplay;
import Frames.ProgramError.Instruction;
import Frames.ProgramError.Report;
import Frames.ProgramError.Troubleshoot;
import java.io.File;

public class NewTabName extends javax.swing.JFrame {

    /** Creates new form NewTabName */
    public NewTabName() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tab Name");
        setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setText("Enter New Tab Name : ");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(tabname, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tabname, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-425)/2, (screenSize.height-158)/2, 425, 158);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(tabname.getText().equals(""))
           return;
       new File(System.getProperty("user.dir").replace('/', '\\')+"\\"+tabname.getText()).mkdirs();
       File f=new File(System.getProperty("user.dir").replace('/', '\\')+"\\"+tabname.getText());
       String[] names=new SortAlphabatically().sort(new File(System.getProperty("user.dir").replace('/', '\\')).list());
       int i=0;
       boolean found=false;
       while(i<names.length){
           if((names[i].lastIndexOf('.')!=-1&&names[i].substring(0, names[i].lastIndexOf('.')).equalsIgnoreCase(tabname.getText()))||(names[i].lastIndexOf('.')==-1&&names[i].equalsIgnoreCase(tabname.getText())))
               found=true;
           i++;
       }
       f.delete();
       if(!found){
           new error_1().setVisible(true);
           return;
        }
       i=0;
       int k=0;
       boolean breaked=false;
       File[] years=new File(pathlocation.getlocation()).listFiles();
       while(i<years.length){
           k=0;
           String[] nameis=years[i].list();
           while(k<nameis.length){
               if(!new File(pathlocation.getlocation().replace('/', '\\')+"\\"+years[i].getName()+"\\"+nameis[k]+"\\"+tabname.getText()).mkdirs()){
                   if(new File(pathlocation.getlocation().replace('/', '\\')+"\\"+years[i].getName()+"\\"+nameis[k]+"\\"+tabname.getText()).exists()){
                       new Instruction("This tab name already exists.").setVisible(true);
                       breaked=true;
                       break;
                   }
                   //bugno sem121D[mJWBjtut
                   final ErrorDisplay err=new ErrorDisplay("sem121D[mJWBjtut");
                   err.setVisible(true);
                   err.addTroubleshootAction(new Troubleshoot() {
                        public void doAction() {
                           new Instruction("An Error Occured. Please close all the open files on this computer and try again. If the problem persists contact your Administrator.").setVisible(true);
                        }
                    });
                    err.addReportAction(new Report() {

                        public void reportAction() {
                            err.addAdditionalReporting("could not make tab folder in name folder");
                        }
                    });
                    return;
               }
           k++;
           }
           if(breaked)
               break;
           i++;
       }
       TypeofBills types=new TypeofBills();
       if(!types.isTabPresent(tabname.getText()))
        types.addNewBillType(tabname.getText(), tabname.getText());
       dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTabName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tabname;
    // End of variables declaration//GEN-END:variables

}
