/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreviewBox.java
 *
 * Created on Mar 12, 2011, 4:17:38 AM
 */

package Printing;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Toolkit;

/**
 *
 * @author ci
 */
public class PreviewBox extends javax.swing.JPanel {

    /** Creates new form PreviewBox */
    public PreviewBox() {
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, 1500);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
public void paint(Graphics g){
        g.clipRect(0,0,Toolkit.getDefaultToolkit().getScreenSize().width , Toolkit.getDefaultToolkit().getScreenSize().height);
        g.setColor(Color.red);
        g.fillRect(0,0,Toolkit.getDefaultToolkit().getScreenSize().width , Toolkit.getDefaultToolkit().getScreenSize().height);
        PreviewPage p=new PreviewPage();
        g.drawImage(p.IMAGE,50,50,null);
        g.setColor(Color.WHITE);
        
    g.drawString("RISHABH", 600, 600);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
